# Generated by Django 5.2.4 on 2025-09-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tidal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tidaltoken",
            name="tidal_user_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
