# Generated by Django 5.2.4 on 2025-09-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tidal", "0002_tidaltoken_tidal_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tidaltoken",
            name="tidal_country",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tidaltoken",
            name="tidal_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tidaltoken",
            name="tidal_username",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
