# Generated by Django 5.2.4 on 2025-09-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tidal", "0003_tidaltoken_tidal_country_tidaltoken_tidal_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tidal_id", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tidal_id", models.CharField(max_length=128, unique=True)),
                ("title", models.CharField(max_length=256)),
                ("ISRC", models.CharField(blank=True, max_length=50, null=True)),
                ("playlists", models.ManyToManyField(related_name="songs", to="tidal.playlist")),
            ],
        ),
    ]
